# Generated by Django 4.0.4 on 2022-09-28 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_guesses', models.FloatField(default=0)),
                ('correct_guesses', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('english_word', models.CharField(max_length=40)),
                ('spanish_word', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40, null=True)),
                ('tries', models.FloatField(default=0)),
                ('wrong_guesses', models.FloatField(default=0)),
                ('correct_guesses', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('user', models.ManyToManyField(through='application.UsersWords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userswords',
            name='words_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.words'),
        ),
    ]
