# Generated by Django 4.0.4 on 2022-09-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userswords',
            name='tries',
            field=models.FloatField(default=0),
        ),
    ]
