# Generated by Django 4.0.4 on 2022-05-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=40)),
                ('spanish_word', models.CharField(max_length=40)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
