# Generated by Django 4.0.4 on 2022-05-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='slug',
        ),
    ]
