# Generated by Django 4.0.4 on 2022-05-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_words_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
