# Generated by Django 4.0.4 on 2022-05-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_words_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='category',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
