# Generated by Django 4.0.4 on 2022-09-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_words_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='correct_guesses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='words',
            name='tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='words',
            name='wrong_guesses',
            field=models.IntegerField(default=0),
        ),
    ]
