# Generated by Django 4.0.4 on 2022-09-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_words_correct_guesses_alter_words_tries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
